using Godot;
using System;
using System.Collections.Generic;
using GameSpace.Constants;
using GameSpace.PawnSpace;
using static UtilsSpace.UtilsFunctions;

namespace GameSpace.CellSpace;

public interface ICell
{
  bool IsOpen { get; set; }
  CellType Type { get; }
}

public partial class Cell : Node3D, ICell
{
  [Export]
  private GridMap _visibleCellElem;
  [Export]
  private PackedScene _invisibleCellScene;
  // that elem will be generated by _invisibleCellScene, and then will be put as child
  private GridMap _invisibleCellElem;
  // random by default and can be changed inside editor, if it still random - forceful change.
  // cell type должен быть классом из списка классов.
  [Export]
  public CellType Type { get; private set; } = CellType.Random;

  private bool _isOpen = false;
  public bool IsOpen
  {
    get { return _isOpen; }
    set
    {
      _isOpen = value;
      ChangeMapsVisibility(value);
    }
  }

  public Vector2 FieldCords { get; set; }
  public List<Pawn> Pawns = new();

  public override void _Ready()
  {
    base._Ready();
    _invisibleCellElem = UnpackInvisibleScene();
    ChangeTypeWhenRandom();
    ChangeMapsVisibility(false);
    AddChild(_invisibleCellElem);
  }

  private void ChangeMapsVisibility(bool value)
  {
    if (value)
    {
      _visibleCellElem.Visible = true;
      _invisibleCellElem.Visible = false;
    }
    else
    {
      _visibleCellElem.Visible = false;
      _invisibleCellElem.Visible = true;
    }
  }

  private void ChangeTypeWhenRandom()
  {
    if (Type != CellType.Random) return;
    Type = GetRandomEnumValueExcluding(CellType.Random);
  }

  private GridMap UnpackInvisibleScene()
  {
    Node instance = _invisibleCellScene?.Instantiate();
    if (_invisibleCellScene == null || instance is not GridMap) return GD.Load<PackedScene>("res://features/Game/components/cell/scenes/hidden_maps/Forest_1.tscn").Instantiate<GridMap>();
    return instance as GridMap;
  }

  public virtual void Modification() { }
}